### ISSUE TITLE
In order to use snippets the user must save the file firstly as a .sl extension

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/atom-cloudslang-package#43]
we should document it

**Comment by oritstone** [comment]
It appears in the documentation that files with .sl extension are recognized as CloudSlang files.
Isn't it clear enough?
![image](https://cloud.githubusercontent.com/assets/7547370/11613251/11023b88-9c23-11e5-9e7f-498400126022.png)

**Comment by roieyal** [comment]
the files are recognized as CloudSlang files but still if you want to use the snippet you must save the file first. (you can't use the snippet on an unsaved file because Atom doesn't know it a sl file) - documentation.

**Comment by oritstone** [comment]
The files are recognized as CloudSlang files only if they are saved as .sl files. And only then the CloudSlang package, including syntax highlighting, auto-completion and snippets can be used...
I think that it is true to any text editor, since a text editor cannot "know" if it is a slang file, JS file, text file, Java file or any other type of file, if the file is not saved with the correct extension.
I don't think we need to document it since it is the common behavior of any text editor
