### ISSUE TITLE
CS icon on atom dark theme

### ISSUE THREAD

**Issue by levice14** [CloudSlang/atom-cloudslang-package#53]
CS icon is not visible on the black theme - by @lrevnic

![cs_icon](https://cloud.githubusercontent.com/assets/8058961/12642983/e978479c-c5c1-11e5-895b-f2a464fdf704.png)

**Comment by SamMarkowitz** [comment]
Atom takes the image from the CloudSlang GitHub page and the font color of the text is very close to the background color. I changed the background there to be white instead of transparent so the text will always show against a white background. Makes it look a little less pretty in GitHub: https://github.com/CloudSlang.

@meshipeer and whoever else feels like weighing in: Is that alright?

**Comment by meshipeer** [comment]
cant we configure the background color?

**Comment by SamMarkowitz** [comment]
Where?

In Atom we can't change the user's settings for their theme, so if we use an image with a transparency, we'll never know what background color it will be up against.

That leaves us with filling in the background color in the image itself so it will always stand out. That same image will appear in Atom and on GitHub. We can choose whatever background we want for that.

**Comment by SamMarkowitz** [comment]
Changed GitHub image.
